### ISSUE TITLE
request for new commands

### ISSUE THREAD

**Issue by a3rgames** [MOXHAFOREVA/mx-servermanbot#3]
hi mx thank you for your amazing script,

I wanted to ask you if you could create two more commands, which would help me a lot

the two commands are -->

/car = give a car to a player with the CAR command through discord

/giveweapon = give a weapon to a player from discord

if you can also create the delete command

thank you lot for your help

**Comment by hasidu** [comment]
I need also bro i was searching how to do that 

Can you help us ? @MOXHAFOREVA

**Comment by MOXHARTZ** [comment]
Hi, unfortunately I can't find time to update this script if u want to add u can use this event `esx:spawnVehicle`

The codes are already very similar to each other u can examine them a little and copy them easily.

**Comment by hasidu** [comment]
Ok bro i will do that and let you know 
Thank you
