### ISSUE TITLE
error while refreshing whitelist

### ISSUE THREAD

**Issue by syno-sy** [MOXHAFOREVA/mx-servermanbot#4]
i have this error on my server console, when i enter refreshwhitelist on my discord server ![mx](https://user-images.githubusercontent.com/89760730/151812744-8680faed-0ef3-4eb9-a4b9-bd0159ca2f27.PNG)

**Comment by koekske** [comment]
i got the same error , any fix?

**Comment by MOXHARTZ** [comment]
It's a problem with token. maybe it's wrong or it's off idk `it's not about the mx-servermanbot`
