### ISSUE TITLE
 @discordjs/uws@10.149.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

### ISSUE THREAD

**Issue by TopperzDK** [MOXHAFOREVA/mx-servermanbot#6]
gettin errors when typing npm i in powershell

@discordjs/uws@10.149.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

resources\mx-bot\node_modules\erlpack
npm ERR! command failed

**Comment by MOXHARTZ** [comment]
just use the builded ver
